Fliplet/fliplet-widget-data-source-provider

- dist/app.js
- src/DataSourceProvider.vue
https://weboo.atlassian.net/browse/OD-81
Fixed behavior of the data source creation when the `Show all data sources` checkbox is checked.
https://share.getcloudapp.com/xQuAKK2O
> [FIx] OD-81 Fixed behavior of the data source creation when the "Show all data sources" checkbox is checked.

- dist/app.js
- src/DataSourceProvider.vue
https://weboo.atlassian.net/browse/OD-85
Added fallback when the selected data source was deleted.
https://share.getcloudapp.com/p9uwggWy
> [Fix] OD-85 When the selected data source was deleted user will be able to select another one.

- dist/app.js
- dist/css/index.css
- src/DataSourceProvider.vue
- src/components/Select2.vue
- src/scss/dataSourceProvider.scss
- src/scss/select2.scss
https://weboo.atlassian.net/browse/OD-99
Added fix for the long data source name. Long data source name will be truncated with an ellipsis
https://share.getcloudapp.com/qGuvj095
> [Fix] OD-99 Long data source name will be truncated with an ellipsis

- dist/app.js
- src/DataSourceProvider.vue
https://weboo.atlassian.net/browse/OD-98
Showing data sources that were created by the user only.
https://share.getcloudapp.com/eDuPQmNJ
> [Fix] OD-98 Showing data sources that were created by the user only.

- dist/app.js
- src/DataSourceProvider.vue
- src/components/Select2.vue
https://weboo.atlassian.net/browse/OD-104
Added new data source provider state when there is no data source for this provider. 
https://share.getcloudapp.com/jkuD7ZGn
> [Fix] OD-104 Fixed data source behavior when there is no data source found.

- dist/app.js
- src/DataSourceProvider.vue
https://weboo.atlassian.net/browse/OD-183
Show security alert only when a component has a default security rules
https://share.getcloudapp.com/NQu1JyWn
> [Fix] OD-183 Show security alert only when a component has a default security rules

- dist/app.js
- src/DataSourceProvider.vue
https://weboo.atlassian.net/browse/OD-103
Change error handler, now we will show an alert with error, allowing a user to continue his work with the data source provider
https://share.getcloudapp.com/v1uxb1RR
> [Fix] OD-103 Change error handler, now we will show an alert with error, allowing a user to continue his work with the data source provider

- dist/app.js
- src/DataSourceProvider.vue
https://weboo.atlassian.net/browse/OD-208 
https://weboo.atlassian.net/browse/OD-209
Fixed selection of the data source
https://share.getcloudapp.com/xQuAx2jG
> [Fix] OD-208 OD-209 Fixed selection of the data source

- dist/app.js
- src/DataSourceProvider.vue
- src/services/dataSource.js
https://weboo.atlassian.net/browse/OD-191
After column change showing updated column names.
https://share.getcloudapp.com/xQuAOmkG
> [Fix] OD-191 After column change showing updated column names.

- dist/app.js
- src/DataSourceProvider.vue
https://weboo.atlassian.net/browse/OD-210
https://weboo.atlassian.net/browse/OD-84
Users could save a newly created data source.
https://share.getcloudapp.com/12urlzB8
https://share.getcloudapp.com/v1uxGRrD
> OD-210 OD-84 [Fix] Users could save a newly created data source.

- dist/app.js
- src/DataSourceProvider.vue
https://weboo.atlassian.net/browse/OD-203
Checking security rules of the data source to warn users if there are rules that are missing.
https://share.getcloudapp.com/QwukoQOY
There is one thing and I'm not sure if that was expected, but as you may see on the video when we adding security rules through the "Configure security rules" button our previously set "write" rule was replaced. To add needed rules I'm using this code:
```
Fliplet.DataSources.update(dataSourceId, {
accessRules: securityRules
});
```
Is it replacing existing security rules with what I've set or it should add my security rules to the existing when I use this API?
> OD-203 [Feature] Checking security rules of the data source to warn users if there are rules that are missing.

- dist/app.js
OD-228 https://weboo.atlassian.net/jira/software/projects/OD/boards/9?selectedIssue=OD-228
Update dist folder
https://screencast-o-matic.com/watch/cYXhXBMiom
@YaroslavOvdii
> OD-228 [Fix] Update dist folder

- dist/app.js
- src/DataSourceProvider.vue
https://weboo.atlassian.net/browse/OD-203
https://weboo.atlassian.net/browse/OD-84
Fixed access rules behavior when multiple rules are added
https://share.getcloudapp.com/WnurP0j2
> OD-203 OD-84 [Fix] Fixed access rules behavior when multiple rules are added

- dist/app.js
- dist/css/index.css
- src/DataSourceProvider.vue
- src/scss/dataSourceProvider.scss
- src/services/dataSource.js
OD-205 https://weboo.atlassian.net/jira/software/projects/OD/boards/9?selectedIssue=OD-205
The loading spinner is displayed and provider disappears
https://screencast-o-matic.com/watch/cYXQQ8MZKo
@YaroslavOvdii @upplabs-alex-levchenko
> OD-227 [Fix] The loading spinner is displayed and provider disappears

- dist/app.js
- src/DataSourceProvider.vue
OD-187 https://weboo.atlassian.net/jira/software/projects/OD/boards/9?selectedIssue=OD-187
Change need help link
@YaroslavOvdii
> OD-187 [Feature] Added need help link to overlay

- dist/app.js
- src/services/dataSource.js
https://weboo.atlassian.net/browse/OD-225
Use fewer attributes from the data source by retrieving only needed attributes
There is no change in data source behavior.
> OD-225 [Feature] Use less attributes from data source by retrieving only needed attributes

- dist/app.js
- src/DataSourceProvider.vue
https://weboo.atlassian.net/browse/OD-203
https://weboo.atlassian.net/browse/OD-84
Fixed access rules behavior when multiple rules are added
https://share.getcloudapp.com/WnurP0j2
A returned solution from this [PR](https://github.com/Fliplet/fliplet-widget-data-source-provider/pull/20) that was accidentally removed in this [PR](https://github.com/Fliplet/fliplet-widget-data-source-provider/pull/21/files#diff-63dfacd6065c5beb85ab057a50d9799712221f2aa310bf799ce6fb834b5b123fL200)
> OD-203 [Fix] Returned previous solution

- dist/app.js
- src/services/dataSource.js
https://weboo.atlassian.net/browse/OD-263
Users can log in with an email witch have an upper case in it
https://share.getcloudapp.com/OAuWwL70
> OD-263 [Fix] Users can log in with an email witch have an upper case in it

- dist/app.js
- src/DataSourceProvider.vue
- src/services/dataSource.js
https://weboo.atlassian.net/browse/OD-247
Showing connected apps in the data source provider.
https://share.getcloudapp.com/z8u4vWbK
Added `type: null` to the `Fliplet.DataSources.get` options so we don't need to filter users' data sources on the front-end.
> OD-247 [Fix] Showing connected apps in the data source provider.

- dist/app.js
- src/DataSourceProvider.vue
- src/services/dataSource.js
https://weboo.atlassian.net/browse/OD-200
Added listener for the updated security rules. For OD-200 and OD-201 to work.
https://screencast-o-matic.com/watch/cYXY6ULTJW
> OD-200 OD-201 [Feature] Listener for the security rules update.

- dist/app.js
- src/DataSourceProvider.vue
@sofiiakvasnevska
OD-215 https://weboo.atlassian.net/browse/OD-215
When `Show all data sources` is unchecked revert to selecting the initial `– Select a data source` value
https://screencast-o-matic.com/watch/cYlV2vN6i0
> OD-215 [Bug] Make Data source not disappearing after unchecking Show all data sources

- dist/app.js
- src/DataSourceProvider.vue
@sofiiakvasnevska
OD-280 https://weboo.atlassian.net/browse/OD-280
Add titles to `Missing security rules` pop-up
https://screencast-o-matic.com/watch/cYlfIDNU4J
> OD-280 [Fix] Add titles to "Missing security rules" pop-up

- dist/app.js
- src/DataSourceProvider.vue
- src/services/dataSource.js
https://weboo.atlassian.net/browse/OD-276
When users will add missing rules and they won't duplicate themselves.
https://share.getcloudapp.com/5zudJBWZ
Also, fix this [bug](https://weboo.atlassian.net/browse/OD-278) by compiling the dist folder.
> OD-276 OD-278 [Fix] When users will add missing rules and they won't duplicate themselves.

- dist/app.js
- src/DataSourceProvider.vue
OD-284 https://weboo.atlassian.net/jira/software/projects/OD/boards/9?selectedIssue=OD-284
Data source provider shows alert 'This data source is missing security rules.' when creating data source using API
https://screencast-o-matic.com/watch/cYl2lJ8IMk
> OD-284 [Fix] 'Data source missing rules' when connected to DS provider via API

- dist/app.js
- src/DataSourceProvider.vue
https://weboo.atlassian.net/browse/OD-265
If the data source has a disabled rule that we need to add and this rule related to all apps or to the current app.
https://share.getcloudapp.com/rRu01OKe
> OD-265 [Feature] Access rules will be working as they should

- dist/app.js
- src/DataSourceProvider.vue
@sofiiakvasnevska
OD-298 https://weboo.atlassian.net/browse/OD-298
Security rules used to be added as one rule because there were assignment of type for validating duplicated rules, now they will separate normally after all validations.
https://screencast-o-matic.com/watch/cYl0oD8J2v
> OD-298 [Fix] Split security rules

- dist/app.js
- src/DataSourceProvider.vue
OD-284 https://weboo.atlassian.net/jira/software/projects/OD/boards/9?selectedIssue=OD-284
Added needed param to default Access Rules to pass the if codition is `hasAccessRules` function
http://somup.com/crVhIF2SM6
@upplabs-alex-levchenko  @ivandevupp
> OD-284 [Fix] Missing sesurity rules message appear when ds has an access rules

- dist/app.js
- src/DataSourceProvider.vue
OD-300 https://weboo.atlassian.net/browse/OD-300
- Added function to add current app to existing security rules
http://somup.com/crnTbVDgb5
@upplabs-alex-levchenko @YaroslavOvdii @ivandevupp
> OD-300 [Feature] Added functionality to current app to existing security rules where possible

- dist/app.js
- src/DataSourceProvider.vue
OD-300 https://weboo.atlassian.net/browse/OD-300
- Added fix to comment - https://weboo.atlassian.net/browse/OD-300?focusedCommentId=16342
http://somup.com/creV2ADGmP
@upplabs-alex-levchenko @YaroslavOvdii @ivandevupp
> OD-300 [Feature] Add current app to existing security rules where possible

- dist/app.js
- package-lock.json
- package.json
- src/DataSourceProvider.vue
- src/main.js
https://weboo.atlassian.net/browse/OD-403
Added the babel polyfills for es5 support, so there will be no errors with IE11
https://share.getcloudapp.com/geu49WYq
@upplabs-alex-levchenko @AndrRyaz
> OD-403 [Fix] Data source provider will be open without errors on IE11

- dist/app.js
- src/DataSourceProvider.vue
OD-447 https://weboo.atlassian.net/browse/OD-447
- Added one more incoming atribute to call data source manager in data source provider
http://somup.com/creUQ4bAeG
@upplabs-alex-levchenko @ivandevupp @YaroslavOvdii
> OD-447 [Fix] Show correct data sources to the user when opened in an overlay for an app

- dist/app.js
- src/DataSourceProvider.vue
- src/main.js
Reverts Fliplet/fliplet-widget-data-source-provider#45
> Revert "OD-403 [Fix] Users will be able to load data source provider"

- dist/app.js
- dist/css/index.css
- src/DataSourceProvider.vue
- src/scss/dataSourceProvider.scss
@sofiiakvasnevska @inna-bieshulia
OD-606 https://weboo.atlassian.net/browse/OD-606
Fixed wrong alignment of data source fields
**Problem:** Default Bootstrap style was limiting "container" width according to iframe size.
**Solution:** Manually set minimal width for "container" class to override Bootstrap behavior.
https://storyxpress.co/video/ksrkin0rayyr4c27d
> OD-606 [Fix] Aligning data source fields

- dist/app.js
- package-lock.json
- package.json
- src/DataSourceProvider.vue
Ref. https://weboo.atlassian.net/browse/ID-3302
> ID-3302 [Feat] Set selected data source based on set-data message

- dist/app.js
- src/DataSourceProvider.vue
Ref. https://weboo.atlassian.net/browse/ID-3302
```js
var dataSourceProvider = Fliplet.Widget.open('com.fliplet.data-source-provider', {
onEvent: function(eventName, data) {
console.log(eventName); // 'selected-data-source-loaded'
console.log(data); // Selected data source ID
}
});
dataSourceProvider.emit('change-data-source'); // Trigger data source change sequence
```
> ID-3302 [Feat] Add support to wait for data source to be loaded and to trigger data source change

- dist/app.js
- src/services/dataSource.js
Ref. https://weboo.atlassian.net/browse/ID-3718
Skip compile: 
Includes translation: 
Initiative: Helper widgetisation
Impact: Medium
Affected: Widgets that use data source provider to manage/create data sources
Verify: DS management works as usual
> ID-3718 [Fix] Make default values optional when initialising the provider

- dist/app.js
- dist/css/index.css
- src/DataSourceProvider.vue
- src/scss/dataSourceProvider.scss
Title | Ticket | PR
-- | -- | --
Adds readonly mode for showing data source selection | ID-4310 | #64
> Release 20240507

- dist/css/index.css
- src/scss/dataSourceProvider.scss
Title | Ticket | PR
-- | -- | --
Tweaks data source provider layout and spacing | ID-4372 | x
> Release 20240514
